name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-mlproject:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
        activate-environment: lstm_gold_price_prediction
        environment-file: MLProject/conda.yaml
        use-mamba: true

    - name: Install MLflow
      run: conda run -n lstm_gold_price_prediction pip install mlflow

    - name: Run MLflow project
      run: |
        conda activate lstm_gold_price_prediction
        mlflow run MLProject --no-conda
